<?php
$lang=array(
	'now'=>'Just now',
	'ago'=>'%s ago',
	'second'=>'second',
	'minute'=>'minute',
	'hour'=>'hour',
	'day'=>'day',
	'date'=>'Date',
	'yesterday'=>'Yesterday %s',
	'the_day_before_yesterday'=>'The day before yesterday at %s',
	'chat'=>'Chat',
	'event'=>'Event',
	'news'=>'News',
	'colon'=>': ',
	'homepage'=>'Home Page',
	'install'=>'Install',
	'support'=>'Support',
	'ranking'=>'Ranking',
	'beatmap'=>'Beatmap',
	'score'=>'Score',
	'performance'=>'Performance',
	'accuracy'=>'Accuracy',
	'playername'=>'Player Name',
	'maxcombo'=>'Max Combo',
	'total_hits'=>'Total Hits',
	'playcount'=>'Play Count',
	'regdate'=>'Register Date',
	'lastlogin'=>'Last Login',
	'bplist'=>'Best Performance',
	'userpage'=>'%s on %s',
	'support*_userpage'=>'%s ♥ %s',
	'fold_or_unfold'=>'Fold/Unfold',
	'never_play_this_mode'=>"The player haven't play this mode yet~",
	'did_not_play_banyou'=>"The player haven't play BanYou yet."
);
?>
