<?php
$lang=array(
	'now'=>'刚刚',
	'ago'=>'%s前',
	'second'=>'秒',
	'minute'=>'分钟',
	'hour'=>'小时',
	'day'=>'天',
	'date'=>'日期',
	'yesterday'=>'昨天 %s',
	'the_day_before_yesterday'=>'前天 %s',
	'chat'=>'聊天',
	'event'=>'事件',
	'news'=>'新闻',
	'colon'=>'：',
	'homepage'=>'首页',
	'install'=>'安装',
	'support'=>'支持',
	'ranking'=>'排名',
	'beatmap'=>'谱面',
	'score'=>'分数',
	'performance'=>'表现',
	'accuracy'=>'准确度',
	'playername'=>'玩家名',
	'maxcombo'=>'最大连击',
	'total_hits'=>'总击打数',
	'playcount'=>'游玩次数',
	'regdate'=>'注册时间',
	'lastlogin'=>'最后上线',
	'bplist'=>'最佳成绩列表',
	'userpage'=>'%s 在 %s',
	'support*_userpage'=>'%s ♥ %s',
	'fold_or_unfold'=>'折叠/展开',
	'never_play_this_mode'=>'这个玩家似乎从未玩过这个模式呢~',
	'did_not_play_banyou'=>'该玩家并没有游玩 BanYou.'
);
?>
